version: '3.7' #Version of YML file

services:
  nodejs-app:
    image: chetan11may/node-app:prod 
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 8085:3000
    networks:
      - overlay



networks:
  overlay:
    external: true
    name: my-overlay

